### ISSUE TITLE
Authentication fails without throwing an exception

### ISSUE THREAD

**Issue by Toyinster** [petercoles/Betfair-Exchange#1]
Hi Peter,

I was trying your package out today and found that I wasn't authenticated when attempting to get events as per your example. As it turns out it was my fault because I had misspelt my environment variable username and password and therefore was passing null through to the auth init method. However, the package did not throw an exception and left me scratching my head as to why I could make a request without a session token. I have a simple fix for this if you are excepting pull requests.

Thanks,

Toyin.

**Comment by petercoles** [comment]
That’s a good point. Yes, I’d love to receive your pull request.

Thanks

Peter

**Comment by Toyinster** [comment]
Cool - I will make one now. Do yo have a branch you want me to make this pull request to?

**Comment by petercoles** [comment]
Good question. Too late for this time, but there's now a develop branch against which to make pull requests.
